// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBX_HjFwXDwt3yW8oiyvVySPJeRJVO1Zaw',
    appId: '1:797834892606:android:4016f51e844fc8c8fdc86f',
    messagingSenderId: '797834892606',
    projectId: 'dbmagang-ec5dc',
    storageBucket: 'dbmagang-ec5dc.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMcmpu3Xe0MIWgvq5DbKeuhCMNpQJQFe4',
    appId: '1:797834892606:web:9f813db4a4f7b2b4fdc86f',
    messagingSenderId: '797834892606',
    projectId: 'dbmagang-ec5dc',
    authDomain: 'dbmagang-ec5dc.firebaseapp.com',
    storageBucket: 'dbmagang-ec5dc.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMcmpu3Xe0MIWgvq5DbKeuhCMNpQJQFe4',
    appId: '1:797834892606:web:9f813db4a4f7b2b4fdc86f',
    messagingSenderId: '797834892606',
    projectId: 'dbmagang-ec5dc',
    authDomain: 'dbmagang-ec5dc.firebaseapp.com',
    storageBucket: 'dbmagang-ec5dc.appspot.com',
  );
}
